wtfornot/config/routes.rb
Wtfornot::Application.routes.draw do
  devise_for :users, :controllers => { :passwords => "passwords" }

  resources :hailwtfornots

  resources :users

  resources :images do
    member do
      post :add_point
    end
  end
  
  root :to => 'hailwtfornots#index'
  match 'new' => 'hailwtfornots#new'
  match ':id' => 'hailwtfornots#show', :id => /\d/

end

wtfornot/app/models/hailwtfornot.rb
class Hailwtfornot < ActiveRecord::Base

  paginates_per 4

  validates :image1, :image2, :presence => true

  belongs_to :image_1, :class_name => 'Image', :foreign_key => :image1
  belongs_to :image_2, :class_name => 'Image', :foreign_key => :image2
  belongs_to :user
 
  after_validation(:on => :create) do
    self.title = self.image_1.name + " Vs " + self.image_2.name if self.title.blank?
  end
 
  def self.create_new params
    hailwtfornot = Hailwtfornot.new(params[:hailwtfornot])

    image1 =  Image.new(params[:image1])
    image2 =  Image.new(params[:image2])

    begin 
      Hailwtfornot.transaction do
        image1.save!
        image2.save!
        hailwtfornot.image1 = image1.id
        hailwtfornot.image2 = image2.id
        hailwtfornot.save!
      end
    rescue ActiveRecord::RecordInvalid
      hailwtfornot.errors.add(:base, image1.errors.full_messages.join(' ')) if image1.errors.any?
      hailwtfornot.errors.add(:base, image2.errors.full_messages.join(' ')) if image2.errors.any?
    end
    hailwtfornot
  end
end

wtfornot/app/controllers/hailwtfornots_controller.rb
class HailwtfornotsController < ApplicationController

  #before_filter :authenticate_user!

  # GET /hailwtfornots
  # GET /hailwtfornots.json
  def index
    @hailwtfornots = Hailwtfornot.order('points DESC').page params[:wtfornot_page]
    @images = Image.order('points DESC').page params[:image_page]
    @users = User.order('points DESC').page params[:user_page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hailwtfornots }
    end
  end

  # GET /hailwtfornots/1
  # GET /hailwtfornots/1.json
  def show
    @hailwtfornot = Hailwtfornot.find(params[:id])
    @image1 = @hailwtfornot.image_1
    @image2 = @hailwtfornot.image_2

    if user_signed_in?
      @wtfornot_user = WtfornotUser.where(:user_id => current_user.id, :wtfornot_id => @hailwtfornot.id).first
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hailwtfornot }
    end
  end

  # GET /hailwtfornots/new
  # GET /hailwtfornots/new.json
  def new
    @hailwtfornot = Hailwtfornot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hailwtfornot }
    end
  end

  # GET /hailwtfornots/1/edit
  def edit
    #@hailwtfornot = Hailwtfornot.find(params[:id])
    raise ActionController::RoutingError.new('Not Found')
  end

  # POST /hailwtfornots
  # POST /hailwtfornots.json
  def create
    @hailwtfornot = Hailwtfornot.create_new params

    respond_to do |format|
      if !@hailwtfornot.errors.any?
        format.html { redirect_to "/#{@hailwtfornot.id}", notice: 'Wtfornot was successfully created.' }
        format.json { render json: @hailwtfornot, status: :created, location: @hailwtfornot }
      else
        format.html { render action: "new" }
        format.json { render json: @hailwtfornot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hailwtfornots/1
  # PUT /hailwtfornots/1.json
  def update
    #@hailwtfornot = Hailwtfornot.find(params[:id])

    #respond_to do |format|
    #  if @hailwtfornot.update_attributes(params[:hailwtfornot])
    #    format.html { redirect_to @hailwtfornot, notice: 'Hailwtfornot was successfully updated.' }
    #    format.json { head :no_content }
    #  else
    #    format.html { render action: "edit" }
    #    format.json { render json: @hailwtfornot.errors, status: :unprocessable_entity }
    #  end
    #end
    raise ActionController::RoutingError.new('Not Found')
  end

  # DELETE /hailwtfornots/1
  # DELETE /hailwtfornots/1.json
  def destroy
    #@hailwtfornot = Hailwtfornot.find(params[:id])
    #@hailwtfornot.destroy

    #respond_to do |format|
    #  format.html { redirect_to hailwtfornots_url }
    #  format.json { head :no_content }
    #end
    raise ActionController::RoutingError.new('Not Found')
  end
end

wtfornot/app/helpers/hailwtfornots_helper.rb
module HailwtfornotsHelper
end

wtfornot/app/views/hailwtfornots/_form.html.haml
= form_for @hailwtfornot, :html => { :multipart => true } do |f|
  - if @hailwtfornot.errors.any?
    #error_explanation
      %h4= "#{pluralize(@hailwtfornot.errors.count, "error")} prohibited this wtfornot from being saved:"

      %ul
        - @hailwtfornot.errors.each do |attr, msg|
          %li= msg

  - if user_signed_in?
    = f.hidden_field :user_id, { value: "#{current_user.id}" }

  .field.form-padding.title
    = f.label :title
    = f.text_field :title
  .field.form-padding.image
    = f.label :image1
    = render :partial => "images/basic_fields", :locals => { :obj => "image1"}

  .field.form-padding.image
    = f.label :image2
    = render :partial => "images/basic_fields", :locals => { :obj => "image2"}
  .actions.form-submit
    = f.submit "Create wtfornot", :class => 'buttonTo'

wtfornot/app/views/hailwtfornots/edit.html.erb
<h1>Editing hailwtfornot</h1>

<%= render 'form' %>

<%= link_to 'Show', @hailwtfornot %> |
<%= link_to 'Back', hailwtfornots_path %>

wtfornot/app/views/hailwtfornots/index.html.haml
= stylesheet_link_tag 'hailwtfornots'
= javascript_include_tag 'hailwtfornots'

.how-strip
  - h = Hailwtfornot.where(:id => 1).first
  = link_to "1. Create your own wtfornot", new_path
  - if h
    = link_to "2. Earn Fucks. See a sample", "#{h.id}"
  = link_to "3. Get featured on the leaderboard", root_url

%h1.center Leaderboard

.box
  %h2 Most fucks given to these images
  %p
    .paginate
      = paginate @images, :param_name => 'image_page'

    - @images.each do |i|
      .image-with-points
        = hidden_field_tag nil, image_path(i), :class => ".hidden"
        = image_tag i.file.url(:medium), :class => 'medium2'
        %p #{i.points} fucks given

.bottom

.box
  %h2 Most fucks given to these wtfornots
  %p
    .paginate
      =paginate @hailwtfornots, :param_name => 'wtfornot_page'

    - @hailwtfornots.each do |h|
      - img1 = h.image_1
      - img2 = h.image_2
      .wtfornot
        = hidden_field_tag nil, "#{h.id}", :class => ".hidden"
        %p.center #{h.points} fucks given
        .left
          %p
            = image_tag img1.file.url(:medium), :class=> 'medium3'
            %h4.vs-index Vs

        .right
          %p
            = image_tag img2.file.url(:medium), :class => 'medium3'

  = button_to "Create your own wtfornot", new_path, :method => :get, :class => "buttonToSmall"
.bottom

.box
  %h2 Most fucks given to these users
  %p
    .paginate
      = paginate @users, :param_name => 'user_page'
    
    - @users.each do |u|
      .user-with-image
        = hidden_field_tag nil, user_path(u), :class => ".hidden"
        .left
          %p #{u.username}
          %p #{u.points} fucks given
        
        .right
          - if u.image
            = image_tag u.image.file.url(:medium), :class => 'medium3'

.bottom

wtfornot/app/views/hailwtfornots/new.html.haml
%h1.center New wtfornot

.center
  = render 'form'

wtfornot/app/views/hailwtfornots/show.html.haml
= stylesheet_link_tag    "hailwtfornots"

%p#notice= notice

.details
  %h1= @hailwtfornot.title

  %p.medium-font
    %b Wtfornot Created By:
    = @hailwtfornot.user ? @hailwtfornot.user.username : User::ANON

  %p.medium-font
    %b.total_fucks_given Total fucks given: #{@hailwtfornot.points}
  
  = button_to "Create your own wtfornot", new_path, :method => :get, :class => "buttonTo"

  %h2 OR

  %br
  %h3 Click on an image to give it a Fuck
  - if !user_signed_in?
    %h3.red (You'll need to sign in to do that)
  %br

  - if @hailwtfornot.user and @hailwtfornot.user == current_user
    %h3.own You created this. So you've already given it a fuck.

  - if !@wtfornot_user.nil?
    %h3.own You've already given it a fuck.

.show
  .left
    %p
      %h4.fucks_given_image1 Fucks Given: #{@image1.points}
      = link_to (image_tag @image1.file.url(:medium), :class=> 'medium'), "#", :class => "img_link", :value => @image1.id, :points => @image1.points, :fucks_given_el => ".fucks_given_image1", :hailwtfornot_id => @hailwtfornot.id, :total_fucks_given_el => '.total_fucks_given', :total_points => @hailwtfornot.points 
      %h1.vs Vs

  .right
    %p
      %h4.fucks_given_image2 Fucks Given: #{@image2.points}
      = link_to (image_tag @image2.file.url(:medium), :class => 'medium'), "#", :class => "img_link", :value => @image2.id, :points => @image2.points, :fucks_given_el => ".fucks_given_image2", :hailwtfornot_id => @hailwtfornot.id, :total_fucks_given_el => '.total_fucks_given', :total_points => @hailwtfornot.points

- if not (!@wtfornot_user.nil? or (@hailwtfornot.user and @hailwtfornot.user == current_user))
  :javascript
    $(".img_link").click(function(e) {
      e.preventDefault();
      hailwtfornot_id = this.getAttribute('hailwtfornot_id')
      image_id = this.getAttribute('value')
      fucks_given = parseInt(this.getAttribute('points'))
      total_fucks_given = parseInt(this.getAttribute('total_points'))
      fucks_given_el = this.getAttribute('fucks_given_el')
      total_fucks_given_el = this.getAttribute('total_fucks_given_el')
      $.post("#{add_point_image_path}", 
        {image_id: image_id, hailwtfornot_id: hailwtfornot_id}, 
        function(data){
          if(data.result == "success"){
            html = "Fucks Given: " + (fucks_given + 1)
            total_fucks_given_html = "Total fucks given: " + (total_fucks_given + 1)
            $(fucks_given_el).html(html)
            $(total_fucks_given_el).html(total_fucks_given_html)
            $(".img_link").css('pointer-events', 'none')
            $(".img_link").css('cursor', 'default')
          }
          else if(data.result == "login") {
            window.location = "#{new_user_session_path}"
          }
          else{
            alert("Failed to give it a fuck")
          }
        }
      )
      return false;
    });